<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PivotBankSeeder extends Seeder
{
    public function run(): void
    {
        $banks = [

            ['bank_code' => '002', 'bank_name' => 'BANK RAKYAT INDONESIA', 'channel_code' => 'BRI'],
            ['bank_code' => '003', 'bank_name' => 'BANK INDONESIA EXIMBANK (formerly Bank Ekspor Indonesia)', 'channel_code' => 'EXIMBANK'],
            ['bank_code' => '008', 'bank_name' => 'BANK MANDIRI', 'channel_code' => 'MANDIRI'],
            ['bank_code' => '009', 'bank_name' => 'BANK NEGARA INDONESIA', 'channel_code' => 'BNI'],
            ['bank_code' => '011', 'bank_name' => 'BANK DANAMON INDONESIA', 'channel_code' => 'DANAMON'],
            ['bank_code' => '011', 'bank_name' => 'BANK DANAMON UUS', 'channel_code' => 'DANAMON_UUS'],
            ['bank_code' => '013', 'bank_name' => 'BANK PERMATA', 'channel_code' => 'PERMATA'],
            ['bank_code' => '013', 'bank_name' => 'BANK PERMATA UUS', 'channel_code' => 'PERMATA_UUS'],
            ['bank_code' => '014', 'bank_name' => 'BANK CENTRAL ASIA (BCA)', 'channel_code' => 'BCA'],
            ['bank_code' => '016', 'bank_name' => 'BANK MAYBANK INDONESIA', 'channel_code' => 'MAYBANK'],
            ['bank_code' => '019', 'bank_name' => 'BANK PANIN INDONESIA', 'channel_code' => 'PANIN'],
            ['bank_code' => '020', 'bank_name' => 'BANK ARTA NIAGA KENCANA', 'channel_code' => 'ARTA_NIAGA_KENCANA'],
            ['bank_code' => '022', 'bank_name' => 'BANK CIMB NIAGA', 'channel_code' => 'CIMB'],
            ['bank_code' => '022', 'bank_name' => 'BANK CIMB NIAGA SYARIAH', 'channel_code' => 'CIMB_SYR'],
            ['bank_code' => '022', 'bank_name' => 'BANK CIMB NIAGA UUS', 'channel_code' => 'CIMB_UUS'],
            ['bank_code' => '023', 'bank_name' => 'BANK UOB INDONESIA', 'channel_code' => 'UOB'],
            ['bank_code' => '023', 'bank_name' => 'TMRW BY UOB INDONESIA', 'channel_code' => 'TMRW'],
            ['bank_code' => '026', 'bank_name' => 'BANK LIPPO', 'channel_code' => 'LIPPO'],
            ['bank_code' => '028', 'bank_name' => 'BANK OCBC NISP', 'channel_code' => 'OCBC'],
            ['bank_code' => '028', 'bank_name' => 'BANK OCBC NISP UUS', 'channel_code' => 'OCBC_UUS'],
            ['bank_code' => '030', 'bank_name' => 'AMERICAN EXPRESS BANK LTD', 'channel_code' => 'AMEX'],
            ['bank_code' => '031', 'bank_name' => 'BANK CITIBANK', 'channel_code' => 'CITIBANK'],
            ['bank_code' => '032', 'bank_name' => 'JP MORGAN CHASE BANK', 'channel_code' => 'JPMORGAN'],
            ['bank_code' => '033', 'bank_name' => 'BANK OF AMERICA MERILL-LYNCH', 'channel_code' => 'BAML'],
            ['bank_code' => '034', 'bank_name' => 'BANK ING INDONESIA', 'channel_code' => 'ING'],
            ['bank_code' => '036', 'bank_name' => 'BANK CCB INDONESIA', 'channel_code' => 'CCB'],
            ['bank_code' => '036', 'bank_name' => 'BANK MULTICOR', 'channel_code' => 'MULTICOR'],
            ['bank_code' => '037', 'bank_name' => 'BANK ARTHA GRAHA INTERNATIONAL', 'channel_code' => 'ARTHA'],
            ['bank_code' => '039', 'bank_name' => 'BANK CREDIT AGRICOLE INDOSUEZ', 'channel_code' => 'CREDIT_AGRICOLE'],
            ['bank_code' => '040', 'bank_name' => 'THE BANGKOK BANK COMPANY', 'channel_code' => 'BANGKOK_BANK'],
            ['bank_code' => '042', 'bank_name' => 'BANK MITSUBISHI UFJ FINANCIAL GROUP (MUFG)', 'channel_code' => 'MUFG'],
            ['bank_code' => '045', 'bank_name' => 'BANK SUMITOMO MITSUI INDONESIA', 'channel_code' => 'SUMITOMO'],
            ['bank_code' => '046', 'bank_name' => 'BANK DBS INDONESIA', 'channel_code' => 'DBS'],
            ['bank_code' => '046', 'bank_name' => 'DIGIBANK', 'channel_code' => 'DIGIBANK'],
            ['bank_code' => '047', 'bank_name' => 'BANK RESONA PERDANIA', 'channel_code' => 'RESONA'],
            ['bank_code' => '048', 'bank_name' => 'BANK MIZUHO INDONESIA', 'channel_code' => 'MIZUHO'],
            ['bank_code' => '050', 'bank_name' => 'BANK STANDARD CHARTERED', 'channel_code' => 'STANDARD_CHARTERED'],
            ['bank_code' => '052', 'bank_name' => 'BANK ABN AMRO', 'channel_code' => 'ABN_AMRO'],
            ['bank_code' => '053', 'bank_name' => 'BANK KEPPEL TATLEE BUANA', 'channel_code' => 'KEPPEL'],
            ['bank_code' => '054', 'bank_name' => 'BANK CAPITAL INDONESIA', 'channel_code' => 'CAPITAL'],
            ['bank_code' => '057', 'bank_name' => 'BANK BNP PARIBAS INDONESIA', 'channel_code' => 'BNP_PARIBAS'],
            ['bank_code' => '059', 'bank_name' => 'KOREAN EXCHANGE BANK DANAMON (KEB Indonesia)', 'channel_code' => 'KEB_INDONESIA'],
            ['bank_code' => '060', 'bank_name' => 'BANK RABOBANK INTERNATIONAL INDONESIA', 'channel_code' => 'RABOBANK'],
            ['bank_code' => '061', 'bank_name' => 'BANK ANZ INDONESIA', 'channel_code' => 'ANZ'],
            ['bank_code' => '067', 'bank_name' => 'DEUTSCHE BANK', 'channel_code' => 'DEUTSCHE'],
            ['bank_code' => '068', 'bank_name' => 'BANK WOORI INDONESIA', 'channel_code' => 'WOORI'],
            ['bank_code' => '069', 'bank_name' => 'BANK OF CHINA', 'channel_code' => 'BOC'],
            ['bank_code' => '076', 'bank_name' => 'BANK BUMI ARTA', 'channel_code' => 'BUMI_ARTA'],
            ['bank_code' => '087', 'bank_name' => 'BANK HSBC', 'channel_code' => 'HSBC'],
            ['bank_code' => '087', 'bank_name' => 'BANK HSBC UUS', 'channel_code' => 'HSBC_UUS'],
            ['bank_code' => '095', 'bank_name' => 'BANK J TRUST INDONESIA', 'channel_code' => 'JTRUST'],
            ['bank_code' => '097', 'bank_name' => 'BANK MAYAPADA', 'channel_code' => 'MAYAPADA'],
            ['bank_code' => '110', 'bank_name' => 'BANK JABAR DAN BANTEN (BJB)', 'channel_code' => 'BJB'],
            ['bank_code' => '111', 'bank_name' => 'BANK DKI', 'channel_code' => 'DKI'],
            ['bank_code' => '112', 'bank_name' => 'BPD DIY', 'channel_code' => 'DAERAH_ISTIMEWA'],
            ['bank_code' => '113', 'bank_name' => 'BPD JAWA TENGAH', 'channel_code' => 'JAWA_TENGAH'],
            ['bank_code' => '114', 'bank_name' => 'BPD JAWA TIMUR', 'channel_code' => 'JAWA_TIMUR'],
            ['bank_code' => '115', 'bank_name' => 'BPD JAMBI', 'channel_code' => 'JAMBI'],
            ['bank_code' => '116', 'bank_name' => 'BPD ACEH', 'channel_code' => 'ACEH'],
            ['bank_code' => '116', 'bank_name' => 'BPD ACEH SYARIAH', 'channel_code' => 'ACEH_SYR'],
            ['bank_code' => '117', 'bank_name' => 'BPD SUMATERA UTARA', 'channel_code' => 'SUMUT'],
            ['bank_code' => '118', 'bank_name' => 'BPD SUMATERA BARAT', 'channel_code' => 'SUMATERA_BARAT'],
            ['bank_code' => '119', 'bank_name' => 'BPD KALIMANTAN TIMUR', 'channel_code' => 'KALIMANTAN_TIMUR'],
            ['bank_code' => '120', 'bank_name' => 'BPD SUMSEL DAN BABEL', 'channel_code' => 'SUMSEL_DAN_BABEL'],
            ['bank_code' => '121', 'bank_name' => 'BPD LAMPUNG', 'channel_code' => 'LAMPUNG'],
            ['bank_code' => '122', 'bank_name' => 'BPD KALIMANTAN SELATAN', 'channel_code' => 'KALIMANTAN_SELATAN'],
            ['bank_code' => '123', 'bank_name' => 'BPD KALIMANTAN BARAT', 'channel_code' => 'KALIMANTAN_BARAT'],
            ['bank_code' => '124', 'bank_name' => 'BANK KALTIM KALTARA', 'channel_code' => 'KALIMANTAN_TIMUR'],
            ['bank_code' => '126', 'bank_name' => 'BPD SULSELBAR', 'channel_code' => 'SULSELBAR'],
            ['bank_code' => '127', 'bank_name' => 'BPD SULUTGO', 'channel_code' => 'SULUT'],
            ['bank_code' => '128', 'bank_name' => 'BPD NTB', 'channel_code' => 'NUSA_TENGGARA_BARAT'],
            ['bank_code' => '129', 'bank_name' => 'BPD BALI', 'channel_code' => 'BALI'],
            ['bank_code' => '130', 'bank_name' => 'BPD NTT', 'channel_code' => 'NUSA_TENGGARA_TIMUR'],
            ['bank_code' => '131', 'bank_name' => 'BPD MALUKU DAN MALUKU UTARA', 'channel_code' => 'MALUKU'],
            ['bank_code' => '132', 'bank_name' => 'BPD PAPUA', 'channel_code' => 'PAPUA'],
            ['bank_code' => '133', 'bank_name' => 'BPD BENGKULU', 'channel_code' => 'BENGKULU'],
            ['bank_code' => '134', 'bank_name' => 'BPD SULAWESI TENGAH', 'channel_code' => 'SULAWESI'],
            ['bank_code' => '135', 'bank_name' => 'BPD SULAWESI TENGGARA', 'channel_code' => 'SULAWESI_TENGGARA'],
            ['bank_code' => '137', 'bank_name' => 'BPD BANTEN', 'channel_code' => 'BANTEN'],
            ['bank_code' => '147', 'bank_name' => 'BANK MUAMALAT', 'channel_code' => 'MUAMALAT'],
            ['bank_code' => '153', 'bank_name' => 'BANK SINARMAS', 'channel_code' => 'SINARMAS'],
            ['bank_code' => '200', 'bank_name' => 'BANK TABUNGAN NEGARA (BTN)', 'channel_code' => 'BTN'],
            ['bank_code' => '213', 'bank_name' => 'BANK SMBC INDONESIA', 'channel_code' => 'SMBC_INDONESIA'],
            ['bank_code' => '213', 'bank_name' => 'JENIUS', 'channel_code' => 'JENIUS'],
            ['bank_code' => '422', 'bank_name' => 'BANK SYARIAH INDONESIA (Formerly BRI Syariah)', 'channel_code' => 'BRI_SYR'],
            ['bank_code' => '425', 'bank_name' => 'BANK JAWA DAN BANTEN (BJB) SYARIAH', 'channel_code' => 'BJB_SYR'],
            ['bank_code' => '426', 'bank_name' => 'BANK MEGA', 'channel_code' => 'MEGA'],
            ['bank_code' => '427', 'bank_name' => 'BANK SYARIAH INDONESIA (Formerly BNI Syariah)', 'channel_code' => 'BNI_SYR'],
            ['bank_code' => '441', 'bank_name' => 'BANK KB BUKOPIN', 'channel_code' => 'BUKOPIN'],
            ['bank_code' => '451', 'bank_name' => 'BANK SYARIAH INDONESIA', 'channel_code' => 'BSI'],
            ['bank_code' => '484', 'bank_name' => 'BANK KEB HANA', 'channel_code' => 'HANA'],
            ['bank_code' => '490', 'bank_name' => 'BANK NEO COMMERCE', 'channel_code' => 'BNC'],
            ['bank_code' => '494', 'bank_name' => 'BANK RAYA', 'channel_code' => 'AGRONIAGA'],
            ['bank_code' => '501', 'bank_name' => 'BANK CENTRAL ASIA DIGITAL (BluBCA)', 'channel_code' => 'BCA_DIGITAL'],
            ['bank_code' => '503', 'bank_name' => 'BANK NATIONAL NOBU', 'channel_code' => 'NATIONALNOBU'],
            ['bank_code' => '506', 'bank_name' => 'BANK MEGA SYARIAH', 'channel_code' => 'MEGA_SYR'],
            ['bank_code' => '517', 'bank_name' => 'BANK PANIN DUBAI SYARIAH', 'channel_code' => 'PANIN_SYR'],
            ['bank_code' => '521', 'bank_name' => 'BANK KB BUKOPIN SYARIAH', 'channel_code' => 'BUKOPIN_SYR'],
            ['bank_code' => '531', 'bank_name' => 'BANK AMAR INDONESIA', 'channel_code' => 'AMAR'],
            ['bank_code' => '535', 'bank_name' => 'SEABANK', 'channel_code' => 'SEABANK'],
            ['bank_code' => '536', 'bank_name' => 'BANK CENTRAL ASIA SYARIAH', 'channel_code' => 'BCA_SYR'],
            ['bank_code' => '542', 'bank_name' => 'BANK JAGO', 'channel_code' => 'JAGO'],
            ['bank_code' => '547', 'bank_name' => 'BANK BTPN SYARIAH', 'channel_code' => 'BTPN_SYARIAH'],
            ['bank_code' => '564', 'bank_name' => 'BANK MANDIRI TASPEN POS', 'channel_code' => 'MANDIRI_TASPEN'],
            ['bank_code' => '567', 'bank_name' => 'ALLO BANK INDONESIA', 'channel_code' => 'HARDA_INTERNASIONAL'],
            ['bank_code' => '867', 'bank_name' => 'BANK EKA BUMI ARTHA', 'channel_code' => 'EKA'],
            ['bank_code' => '945', 'bank_name' => 'BANK IBK INDONESIA', 'channel_code' => 'IBK'],
            ['bank_code' => '947', 'bank_name' => 'BANK ALADIN SYARIAH', 'channel_code' => 'ALADIN'],
            ['bank_code' => '948', 'bank_name' => 'BANK OCBC INDONESIA', 'channel_code' => 'OCBC_INDONESIA'],
            ['bank_code' => '949', 'bank_name' => 'BANK CTBC INDONESIA', 'channel_code' => 'CTBC'],
            ['bank_code' => '950', 'bank_name' => 'BANK COMMONWEALTH', 'channel_code' => 'COMMONWEALTH'],

        ];

        foreach ($banks as $bank) {
            DB::table('pivot_banks')->updateOrInsert(
                ['channel_code' => $bank['channel_code']],
                $bank
            );
        }
    }
}